title: Ed Britton
description: My stuff online.
google_analytics: 
show_downloads: false
lang: en_GB

seo:
  type: website

author:
  name: Ed Britton
  twitter: edbritton

twitter:
  username: edbritton
  card: summary

social:
  name: Ed Britton
  links:
    - https://twitter.com/edbritton
    - https://github.com/edbritton
    - https://www.printables.com/social/176036-ted
    - https://youtube.com/edbritton
    - https://imdb.com/name/nm10740536

permalink: /:categories/:short_year:y_day/

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag

jekyll-mentions: https://twitter.com